<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Mail\NewUserActivationMail;
use App\Models\Profil;
use App\Models\User;
use App\Models\Voiture;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Str;
use Illuminate\View\View;
use Throwable;

class RegisteredUserController extends Controller
{
    /**
     * Display the registration view.
     */
    public function create(): View
    {
        return view('auth.register');
    }

    /**
     * Handle an incoming registration request.
     *
     * This route is restricted to authenticated admin/referent users (see routes/auth.php).
     * A temporary password is generated by the system and sent by email along with an
     * activation link (password reset form) so the user can choose their own password.
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            // Auth (table users)
            'email' => ['required', 'string', 'lowercase', 'email', 'max:255', 'unique:users,email'],

            // Métier (profil)
            'prenom' => ['required', 'string', 'max:100'],
            'nom' => ['required', 'string', 'max:100'],
            'date_naissance' => ['required', 'date'],
            'num_tel' => ['nullable', 'regex:/^\d{10}$/'],

            'adresse' => ['required', 'string', 'max:255'],
            'ville' => ['required', 'string', 'max:100'],
            'code_postale' => ['required', 'regex:/^\d{5}$/'],
            'num_fixe' => ['nullable', 'regex:/^\d{10}$/'],

            'role_profil' => ['required', 'in:referent,benevole,bienfaiteur'],

            // Voiture (table voiture)
            'has_voiture' => ['nullable', 'boolean'],
            'num_immatriculation' => ['nullable', 'string', 'max:50', 'required_if:has_voiture,1', 'regex:/^[A-Z]{2}-\d{3}-[A-Z]{2}$/i'],
            'puissance_voiture' => ['nullable', 'integer', 'min:1', 'required_if:has_voiture,1'],
        ], [
            'prenom.required' => 'Le prénom est obligatoire.',
            'nom.required' => 'Le nom est obligatoire.',
            'date_naissance.required' => 'La date de naissance est obligatoire.',
            'email.required' => 'L\'email est obligatoire.',
            'email.email' => 'Merci de saisir une adresse email valide.',
            'adresse.required' => 'L\'adresse est obligatoire.',
            'ville.required' => 'La ville est obligatoire.',
            'code_postale.required' => 'Le code postal est obligatoire.',
            'code_postale.regex' => 'Le code postal doit contenir 5 chiffres.',
            'num_tel.regex' => 'Le téléphone doit contenir 10 chiffres.',
            'num_fixe.regex' => 'Le numéro fixe doit contenir 10 chiffres.',
            'role_profil.required' => 'Le rôle est obligatoire.',
            'num_immatriculation.required_if' => 'Merci de saisir le numéro d\'immatriculation.',
            'num_immatriculation.regex' => 'Le numéro d\'immatriculation doit être au format AB-123-CD.',
            'puissance_voiture.required_if' => 'Merci de saisir la puissance de la voiture.',
            'puissance_voiture.integer' => 'La puissance doit être un nombre entier.',
            'puissance_voiture.min' => 'La puissance doit être supérieure à 0.',
        ]);

        $temporaryPassword = Str::random(10) . (string) random_int(10, 99);

        $user = null;

        DB::transaction(function () use ($request, &$user, $temporaryPassword): void {
            $user = User::create([
                'email' => $request->email,
                'password' => Hash::make($temporaryPassword),
                'actif' => 1,
            ]);

            Profil::create([
                'user_id' => $user->id,
                'nom' => $request->nom,
                'prenom' => $request->prenom,
                'date_naissance' => $request->date_naissance,
                'num_tel' => $request->num_tel,
                'num_fixe' => $request->num_fixe,
                'adresse' => $request->adresse,
                'code_postale' => $request->code_postale,
                'ville' => $request->ville,
                'role' => $request->role_profil,
                'est_valide' => 0,
                'actif' => 1,
            ]);

            if ($request->boolean('has_voiture')) {
                Voiture::create([
                    'user_id' => $user->id,
                    'num_immatriculation' => $request->num_immatriculation,
                    'puissance_voiture' => $request->puissance_voiture,
                ]);
            }
        });

        event(new Registered($user));

        // Send activation email with temporary password + reset link
        try {
            $token = Password::broker()->createToken($user);
            $activationUrl = url(route('password.reset', ['token' => $token, 'email' => $user->email], false));
            $loginUrl = url(route('login', [], false));

            Mail::to($user->email)->send(new NewUserActivationMail(
                tempPassword: $temporaryPassword,
                activationUrl: $activationUrl,
                loginUrl: $loginUrl,
            ));
        } catch (Throwable $e) {
            Log::error('Failed to send new user activation email', [
                'email' => $user?->email,
                'error' => $e->getMessage(),
            ]);
        }

        // Keep creator session if created by admin/referent
        $creator = auth()->user();
        $creatorCanManage = $creator && ($creator->is_admin || optional($creator->profil)->role === 'referent');

        if (!$creatorCanManage) {
            Auth::login($user);
            return redirect(route('dashboard', absolute: false));
        }

        return redirect()->route('user.index')->with(
            'success',
            'Utilisateur créé avec succès. Un email avec un mot de passe temporaire et un lien d\'activation a été envoyé.'
        );
    }
}
